# Generated by Django 5.0.4 on 2024-04-16 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_patient_p_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='p_id',
            field=models.CharField(default=12345678, max_length=100),
            preserve_default=False,
        ),
    ]
