# Generated by Django 4.2.11 on 2024-04-19 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_doctor_doctor_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='doctor_Name',
            new_name='doctor_name',
        ),
    ]
