# Generated by Django 4.2.11 on 2024-04-19 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_doctor_name_doctor_doctor_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='doctor_name',
            new_name='doctor_Name',
        ),
    ]
