# Generated by Django 4.2.11 on 2024-04-19 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_doctor_name_doctor_doctor_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='p_id',
            new_name='d_id',
        ),
    ]
