# Generated by Django 4.2.11 on 2024-04-19 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_doctor_d_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='p_id',
            field=models.CharField(default=1234, max_length=100),
            preserve_default=False,
        ),
    ]
