# Generated by Django 5.0.4 on 2024-04-19 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_p_id_doctor_d_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='APPOINT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('doctor_name', models.CharField(max_length=100)),
                ('appointment_date', models.CharField(max_length=100)),
                ('time_slot', models.CharField(max_length=100)),
                ('token_number', models.CharField(max_length=100)),
                ('problem', models.TextField()),
            ],
        ),
    ]
