# Generated by Django 5.0.4 on 2024-04-19 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_appoint'),
    ]

    operations = [
        migrations.DeleteModel(
            name='APPOINT',
        ),
    ]
