# Generated by Django 5.0.4 on 2024-04-20 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_patient_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='role',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
