# Generated by Django 4.2.11 on 2024-04-20 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_appoint_remove_doctor_role_remove_patient_role'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='APPOINT',
            new_name='Appointment',
        ),
    ]
