# Generated by Django 4.2.11 on 2024-04-20 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_rename_appoint_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='patient_name',
            field=models.CharField(default='patient_name', max_length=100),
            preserve_default=False,
        ),
    ]
