# Generated by Django 4.2.11 on 2024-04-20 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_appointment_patient_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='patient_id',
            new_name='p_id',
        ),
    ]
