# Generated by Django 4.2.11 on 2024-04-20 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_rename_patient_id_appointment_p_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='a_id',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
    ]
