# Generated by Django 4.2.11 on 2024-04-21 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_rename_appointment_appoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='status',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
    ]
