# Generated by Django 4.2.11 on 2024-04-21 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_patient_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appoint',
            name='status',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='status',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
    ]
