# Generated by Django 4.2.11 on 2024-04-21 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_appoint_status_doctor_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appoint',
            old_name='p_id',
            new_name='pa_id',
        ),
    ]
