# Generated by Django 4.2.11 on 2024-04-21 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_rename_doctor_name_appoint_d_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_id', models.CharField(max_length=100)),
                ('patient_name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('doctor_name', models.CharField(max_length=100)),
                ('admission_date', models.CharField(max_length=100)),
                ('discharge_date', models.CharField(max_length=100)),
                ('service_name', models.CharField(max_length=100)),
                ('cost_of_treatment', models.CharField(max_length=100)),
                ('discount', models.CharField(max_length=100)),
                ('advance_paid', models.CharField(max_length=100)),
                ('Payment_type', models.CharField(max_length=100)),
                ('card_no', models.CharField(max_length=100)),
            ],
        ),
    ]
