# Generated by Django 4.2.11 on 2024-04-21 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='p_id',
            new_name='pp_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
    ]
