# Generated by Django 4.2.11 on 2024-04-22 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_rename_p_id_payment_pp_id_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=100)),
                ('room_type', models.CharField(max_length=100)),
                ('patient_name', models.CharField(max_length=100)),
                ('allotment_date', models.CharField(max_length=100)),
                ('discharge_date', models.CharField(max_length=100)),
                ('doctor_name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
    ]
