# Generated by Django 4.2.11 on 2024-04-30 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='patient_Name',
            new_name='patient_name',
        ),
    ]
