# Generated by Django 4.2.11 on 2024-04-30 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_rename_patient_name_patient_patient_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='age',
            field=models.CharField(max_length=100),
        ),
    ]
