# Generated by Django 4.2.11 on 2024-05-04 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_patient_p_add'),
    ]

    operations = [
        migrations.AddField(
            model_name='appoint',
            name='a_add',
            field=models.CharField(default='None', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='d_add',
            field=models.CharField(default='None', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='py_add',
            field=models.CharField(default='None', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='r_add',
            field=models.CharField(default='None', max_length=100),
            preserve_default=False,
        ),
    ]
