# Generated by Django 4.2.11 on 2024-05-06 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_appoint_a_add_doctor_d_add_payment_py_add_room_r_add'),
    ]

    operations = [
        migrations.CreateModel(
            name='blooddonner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_add', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('date_of_birth', models.CharField(max_length=100)),
                ('blood_group', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('last_donation', models.CharField(max_length=100)),
            ],
        ),
    ]
