# Generated by Django 5.0.4 on 2024-05-09 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_blooddonner'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='phone',
            field=models.IntegerField(default='None'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='srvice_cost',
            field=models.CharField(default='None', max_length=100),
            preserve_default=False,
        ),
    ]
