# Generated by Django 4.2.11 on 2024-05-09 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_alter_payment_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='phone',
        ),
    ]
