# Generated by Django 4.2.11 on 2024-05-09 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_remove_payment_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='phone1',
            field=models.CharField(default=9, max_length=100),
        ),
    ]
