# Generated by Django 5.0.4 on 2024-05-09 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_payment_phone1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='phone1',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='srvice_cost',
        ),
    ]
