# Generated by Django 4.2.11 on 2024-05-09 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_remove_payment_phone1_remove_payment_srvice_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='phone',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='service_cost',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
