# Generated by Django 4.2.11 on 2024-05-10 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_payment_phone_payment_service_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewDoctorForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
