# Generated by Django 4.2.11 on 2024-05-10 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_newdoctorform'),
    ]

    operations = [
        migrations.AddField(
            model_name='newdoctorform',
            name='address',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='newdoctorform',
            name='age',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='newdoctorform',
            name='email',
            field=models.EmailField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='newdoctorform',
            name='first_name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='newdoctorform',
            name='gender',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='newdoctorform',
            name='last_name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='newdoctorform',
            name='phone',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='newdoctorform',
            name='qualifications',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
