# Generated by Django 4.2.11 on 2024-05-10 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_newdoctorform_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newdoctorform',
            name='address',
            field=models.TextField(),
        ),
    ]
