# Generated by Django 4.2.11 on 2024-05-10 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_alter_newdoctorform_address'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewDoctorForm',
            new_name='Dform',
        ),
    ]
