# Generated by Django 4.2.11 on 2024-05-10 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='boss_photo',
            field=models.ImageField(blank=True, default='', upload_to='boss_photos/'),
        ),
    ]
