# Generated by Django 4.2.11 on 2024-05-10 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_alter_contract_boss_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='boss_photo',
            field=models.ImageField(blank=True, upload_to='boss_photos/'),
        ),
    ]
