# Generated by Django 4.2.11 on 2024-05-17 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_alter_contract_boss_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='addmission_date',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
