# Generated by Django 4.2.11 on 2024-05-17 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0061_remove_patient_addmission_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='addmission_date',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
