# Generated by Django 4.2.11 on 2024-05-17 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0063_alter_patient_addmission_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
