# Generated by Django 4.2.11 on 2024-05-18 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0065_alter_patient_addmission_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='addmission_date',
            field=models.TextField(blank=True, null=True),
        ),
    ]
