# Generated by Django 4.2.11 on 2024-05-18 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0067_remove_patient_addmission_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='date',
            field=models.TextField(default=''),
        ),
    ]
