# Generated by Django 4.2.11 on 2024-05-18 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0068_patient_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='address',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='advance_paid',
        ),
    ]
