# Generated by Django 4.2.11 on 2024-05-18 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0070_payment_py_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='card',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date',
            field=models.CharField(default='', max_length=100),
        ),
    ]
